--function Dig(p_Args)
--    local pos, min, max
--
--end
--
--local m_Work = {
--    Dig = {
--        callable = true,
--        func = Dig,
--        prams = {
--            pos = {
--                length = 3
--            },
--            min = {
--                length = 3
--            },
--            max = {
--                length = 3
--            }
--        }
--    }
--}
--
--local m_Queue = {}
